### ISSUE TITLE
Example groovy scripts call conan test_package that no longer exists 

### ISSUE THREAD

**Issue by keelerad** [lasote/skynet_example#6]
This is out of date with the current state of conan

The Simplebuild groovy script calls conan test_package which is no longer a conan command

     client.run(command: "test_package --update --profile \"" + conf_repo_dir + "/" + params.profile 

There is now conan test but this seems to require a whole bunch of extra parameters

Is there an updated example for us beginners anywhere ?

Alec Keeler, Build and Release Engineer Nexor Ltd.

**Comment by lasote** [comment]
Hi, I've updated the repository to use the new conan commands, thanks @jroquelaure for your work!

**Comment by lasote** [comment]
Feel free to write again if you find any issue.
